debug: false

settings:
  currency-symbol: "$"
  lore-message: "<white>Worth: <gold>{currency-symbol}{worth}<white>/pc"
  #----------Shop Integration for worth------------
  #all integrations will still read the item's description from worth.yml
  #available options: EconomyShopGUI (will read all shops and their sell values)
  #none (will use worth.yml for prices)
  integration: "none"
